# Generated by Django 2.2.6 on 2020-01-05 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingId', models.AutoField(primary_key=True, serialize=False)),
                ('dateFrom', models.DateField(blank=True, null=True)),
                ('dateTo', models.DateField(blank=True, null=True)),
                ('roomCount', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('creditCardId', models.AutoField(primary_key=True, serialize=False)),
                ('cardNumber', models.CharField(default='', max_length=20)),
                ('ccv', models.CharField(default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationId', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=100)),
                ('phoneNumber', models.CharField(default='', max_length=20)),
                ('emailAddress', models.CharField(default='', max_length=100)),
                ('webSiteAddress', models.CharField(default='', max_length=255)),
                ('imagePath', models.ImageField(upload_to='')),
                ('nrOfRooms', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomId', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('price', models.FloatField(default=0.0)),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.Location')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('roomTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=300)),
                ('roomType', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=30)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=100)),
                ('phoneNumber', models.CharField(default='', max_length=20)),
                ('emailAddress', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooked',
            fields=[
                ('roomBookedId', models.AutoField(primary_key=True, serialize=False)),
                ('bookingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.Booking')),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.Room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='roomTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.RoomType'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewId', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.Location')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('bookingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.Booking')),
                ('creditCardId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.CreditCard')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.User'),
        ),
        migrations.AddField(
            model_name='booking',
            name='locationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.Location'),
        ),
        migrations.AddField(
            model_name='booking',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.User'),
        ),
    ]
