# Generated by Django 2.2.6 on 2020-01-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0003_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emailAddress',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
