# Generated by Django 2.2.6 on 2020-01-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0004_auto_20200108_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='imagePath',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
